import React from 'react';

import './style.scss';

export default function Content() {
  return (
    <div className='content'>Content
      Lorem ipsum dolor sit amet, consectetur adipisicing elit. Explicabo magni voluptates enim ducimus saepe blanditiis recusandae autem voluptatem ullam distinctio numquam deleniti commodi odit amet porro dicta cumque, atque ratione rerum. Quo quisquam quaerat mollitia a nemo debitis perferendis sit repellat in, ab expedita ullam soluta possimus quasi vero dolorem dolores velit dicta excepturi fugit vel eligendi corporis. Ipsa voluptatum aliquid dolor iusto sed ut aliquam doloremque rerum, amet ullam illum, sapiente quo excepturi, vel consectetur nulla deserunt autem assumenda. Voluptatem laboriosam, possimus delectus mollitia earum provident, eaque eveniet nesciunt et, aut dignissimos iure vitae incidunt est? Atque nihil quis libero modi exercitationem blanditiis deserunt recusandae, voluptates explicabo qui tenetur quisquam ipsum eius perspiciatis cum ducimus? Neque iste distinctio quam aperiam impedit asperiores minus maiores amet, quidem ipsum error, voluptates ad repellat eaque dolores est nihil. Asperiores aut fugit totam, magni deserunt ad illum cum odit doloribus, corrupti tempore eaque blanditiis eum quae ut natus beatae autem quod eligendi sint. Voluptatum magni nisi facilis ad, aut tenetur consequuntur dolor quod reprehenderit. Aperiam ut impedit nobis aut, consectetur suscipit reprehenderit provident beatae perspiciatis natus autem quasi blanditiis nesciunt laboriosam fuga illum ipsum sint doloremque tempora illo adipisci tenetur omnis odio. Enim quaerat obcaecati, cupiditate nemo minus odit eius laborum fuga quidem, provident rerum quisquam quibusdam sit asperiores neque repellendus ipsam? Facere, labore distinctio? Ut dolorem, earum, iure suscipit quod ex sint temporibus porro quam quae aut fugiat impedit illo odio, accusantium cum iste ea autem minus accusamus! Error nam magnam assumenda aut maiores necessitatibus, distinctio nesciunt aliquam illum velit omnis rerum, quae iste quia obcaecati possimus repellat quam! Molestias amet perspiciatis aspernatur cupiditate rerum animi quas modi, qui odit error repellat pariatur eius esse doloremque in a. Ipsum porro, possimus ullam error aliquid nihil enim. Eaque rerum at nemo soluta ratione.
    </div>
  );
}
