import React from 'react';

import './style.scss';

export default function Footer() {
  return (
    <div className='footer'>Footer
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam minus nisi laborum cumque, laboriosam aut reiciendis, a magni incidunt deserunt omnis quis error accusamus eum perferendis sit quasi ea suscipit, voluptates voluptatem. Saepe porro ea, a eius facere architecto ullam error veniam. Quaerat nisi facilis libero similique a mollitia, aliquid voluptate adipisci. Eligendi autem alias, aut et earum fugiat nesciunt laborum quisquam non sapiente voluptas asperiores nam cumque atque corporis amet inventore blanditiis cum fuga reprehenderit dicta magnam? Fugit officia quas doloribus voluptatem exercitationem dolores voluptatum ipsam quae in perferendis quo non, officiis quasi eligendi minus consequuntur minima, vitae expedita cupiditate aperiam nulla? Iste natus ratione officia dolore architecto nulla alias nesciunt autem a quo ad, quasi sapiente, rem necessitatibus eum, voluptas laboriosam repellat earum neque. Quo, numquam cum quos consequatur recusandae nesciunt quasi iure dolores inventore culpa optio eos ratione necessitatibus illum corrupti tempora corporis assumenda odit fuga quam illo accusantium porro iste incidunt. Praesentium necessitatibus optio, nulla autem sapiente adipisci aliquid, illo delectus, nobis perspiciatis molestias? Assumenda sapiente nam asperiores velit beatae earum odit perferendis, adipisci ad, voluptates eveniet repudiandae quasi fugiat. Fugit voluptate rem suscipit animi doloribus vel veniam neque praesentium aspernatur mollitia saepe, provident, esse accusamus assumenda. Dolor voluptas, alias aperiam quisquam consequatur facere, iusto veritatis tempore quae, perferendis ipsam delectus facilis consectetur quia repellendus. Nisi, libero repudiandae! Optio dignissimos alias debitis nisi eius, delectus laborum, quasi labore aspernatur esse, dolorem consequuntur saepe ab eligendi assumenda commodi nostrum. Labore, error! Animi consequuntur corporis recusandae dignissimos iste impedit asperiores numquam ea maxime facere dolore esse quia aspernatur blanditiis id autem consequatur sunt reiciendis illo, quisquam excepturi sed omnis. Minima modi odio, rerum quos temporibus earum recusandae tempore ut adipisci nihil commodi vitae optio alias sed molestias ex consequuntur, explicabo architecto dignissimos, tenetur quis illo ducimus! Non, labore?
    </div>
  );
}
